routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
Auth::routes();
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::group(['middleware' => 'auth'], function () {
Route::get('/', 'DashboardController@index');
Route::get('/home', 'HomeController@index');
Route::resource('categories','ProductCategoryController');
Route::resource('types','ProductTypeController');
Route::resource('products','ProductController',['only'=>['index', 'show', 'edit', 'create', 'store', 'update', 'destroy']]);
Route::get('/import_product','ProductController@indexImport');
Route::post('/proses_import','ProductController@prosesImport');
Route::get('product-number','ProductController@sizeNumber');
Route::get('product-size','ProductController@size');
Route::get('product-types','ProductController@type');
Route::get('payment-types','ProductController@payment');    
Route::get('product-category','ProductController@productCategory');
Route::resource('customers','CustomerController',['only'=>['index', 'show', 'edit', 'create', 'store', 'update', 'destroy']]);
Route::get('customers/edit/{id}', 'CustomerController@edit');
Route::resource('receipts', 'ReceiptController',['only'=>['index', 'show', 'create', 'store']]);
Route::get('/loadProducts','ReceiptController@loadProduct');
Route::get('/addOrder','ReceiptController@addOrder');

Route::resource('sales_orders','SalesOrderController',['only'=>['index', 'show', 'create', 'store']]);
Route::get('/findCustomer', 'SalesOrderController@findCustomer' );
Route::get('/loadProductSales', 'SalesOrderController@loadProductSales');
Route::get('/addSalesOrder', 'SalesOrderController@addOrder');
Route::resource('users','UserController');
Route::resource('roles','RoleController');
Route::resource('report_so','ReportSoController');
Route::get('report_so_daily','ReportSoController@salesOrderDaily');
Route::get('roles/edit/{id}', 'RoleController@edit');
Route::get('/report_by_customer', 'CustomerController@reportCustomer');
Route::get('/report_by_po','ProductController@receiptWeek');
Route::get('/report_by_sell','ProductController@sellWeek');
Route::get('/report_so_by_range', 'ReportSoController@index');
Route::resource('report_stock','StockProductController');
Route::get('/export_product','StockProductController@exportExcelProduct');
Route::get('/report_mounth','ReportSoController@salesOrderMounth');
Route::get('/print_data_report','ReportSoController@printDataSellout');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Zizaco\Entrust\Traits\EntrustUserTrait;

class User extends Authenticatable
{
    use EntrustUserTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\user;
use App\Role;
use Hash;
use DB;
class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index(){
        $data = User::all();
        return view('user.index',compact('data'));
    }

    public function create(){
        $roles = Role::pluck('display_name','id');
        return view('user.create',compact('roles'));
    }

    public function store(){
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required|email|unique:users,email',
            'password' => 'required|same:confirm-password',
            'roles' => 'required'
        ]);

        $input = $request->all();
        // return $request->all();


        $input['password'] = Hash::make($input['password']);
        $user = User::create($input);
        foreach ($request->input('roles') as $key => $value) {
            $user->attachRole($value);
        }

        return redirect('users');
    }

    public function edit($id){
        $user = User::find($id);
        $roles = Role::pluck('display_name','id');
        $userRole = $user->roles->pluck('id','id')->toArray();

        return view('user.edit',compact('user','roles','userRole'));
    }

    public function update(Request $request,$id){
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required|email|unique:users,email,'.$id,
            'password' => 'same:confirm-password',
            'roles' => 'required'
        ]);

        $input = $request->all();
        if(!empty($input['password'])){ 
            $input['password'] = Hash::make($input['password']);
        }else{
            $input = array_except($input,array('password'));    
        }

        $user = User::find($id);
        $user->update($input);
        DB::table('role_user')->where('user_id',$id)->delete();

        
        foreach ($request->input('roles') as $key => $value) {
            $user->attachRole($value);
        }

        return redirect('users');
    }


    public function destroy($id){
    $user = User::find($id);
    if($user) {
      User::destroy($id);
      return redirect('users');
    } else {
      return redirect('users');
    }
    }
}

resources/views/user/create.blade.php
@extends('layouts.default')
@section('content')
@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
<section class="panel panel-default">
	<header class="panel-heading font-bold">
                  Insert User
</header>
    <div class="panel-body">
    {!! Form::open(['url' => 'users', 'class' => 'form-horizontal','files' => true]) !!}
        <div class="form-group">
          <label class="col-sm-2 control-label" for="input-id-1">Name</label>
        	<div class="col-sm-4">
              {!! Form::text('name', null, array('placeholder' => 'Name','class' => 'form-control')) !!}
              </div>
          <input type="hidden" name="active" value="1">
        </div>

           <div class="form-group">
          <label class="col-sm-2 control-label" for="input-id-1">Email</label>
          <div class="col-sm-4">
              {!! Form::text('email', null, array('placeholder' => 'Email','class' => 'form-control')) !!}
              </div>
          <input type="hidden" name="status" value="1">
        </div>

        <div class="form-group">
          <label class="col-sm-2 control-label" for="input-id-1">Password</label>
          <div class="col-sm-4">
              {!! Form::password('password', array('placeholder' => 'Password','class' => 'form-control')) !!}
              </div>
        </div>

        <div class="form-group">
          <label class="col-sm-2 control-label" for="input-id-1">Confirm Password</label>
          <div class="col-sm-4">
               {!! Form::password('confirm-password', array('placeholder' => 'Confirm Password','class' => 'form-control')) !!}
              </div>
        </div>

        <div class="form-group">
          <label class="col-sm-2 control-label" for="input-id-1">Roles</label>
        	<div class="col-sm-4">
        {{Form::select('role_id',$roles,null,['class' => 'form-control m-t chosen-select','placeholder'=>'Select Role User','required'=>true])}}
        </div>

         <div class="line line-dashed b-b line-lg pull-in"></div>
            <div class="form-group">
        <div class="col-sm-offset-2 col-sm-4">
            {!! Form::submit('Create', ['class' => 'btn btn-primary form-control',
                                        'id' => 'submit']) !!}
        </div>
    </div>
    </div>
    {{Form::close()}}
    </div>
</section>	

@endsection

resources/views/user/edit.blade.php
@extends('layouts.default')
@section('content')
@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
<section class="panel panel-default">
    <header class="panel-heading font-bold">Edit Users</header>
    <div class="panel-body">
    {!! Form::model($user, ['method' => 'PATCH','route' => ['users.update', $user->id], 'class' => 'form-horizontal']) !!}
    <div class="form-group">
          <label class="col-sm-2 control-label" for="input-id-1">Name</label>
            <div class="col-sm-4">
                {!! Form::text('name', null, array('placeholder' => 'Name','class' => 'form-control')) !!}
              </div>
    </div>
    <div class="form-group">
          <label class="col-sm-2 control-label" for="input-id-1">Email</label>
          <div class="col-sm-6">
                {!! Form::text('email', null, array('placeholder' => 'Email','class' => 'form-control')) !!}
              </div>
    </div>

    <div class="form-group">
          <label class="col-sm-2 control-label" for="input-id-1">Password</label>
          <div class="col-sm-6">
                {!! Form::password('password', array('placeholder' => 'Password','class' => 'form-control')) !!}
              </div>
    </div>

    <div class="form-group">
          <label class="col-sm-2 control-label" for="input-id-1">Confirm Password</label>
          <div class="col-sm-6">
                {!! Form::password('confirm-password', array('placeholder' => 'Confirm Password','class' => 'form-control')) !!}
              </div>
    </div>

        <div class="form-group">
          <label class="col-sm-2 control-label" for="input-id-1">Roles</label>
          <div class="col-sm-6">
                {!! Form::select('roles[]', $roles,$userRole, array('class' => 'form-control','multiple')) !!}
              </div>
    </div>

             <div class="line line-dashed b-b line-lg pull-in"></div>
            <div class="form-group">
        <div class="col-sm-offset-2 col-sm-4">
            {!! Form::submit('Update', ['class' => 'btn btn-primary form-control',
                                        'id' => 'submit']) !!}
        </div>
    </div>
</section>
@endsection

resources/views/user/index.blade.php
@extends('layouts.default')
@section('content')
  <section class="scrollable padder">
    <section class="panel panel-default">
      <header class="panel-heading">
        Data User
        <a href="{{ URL('users/create') }}" class="btn btn-primary pull-right btn-sm">Add User</a><br>
        <i class="fa fa-info-sign text-muted" data-toggle="tooltip" data-placement="bottom" data-title="ajax to load the data."></i> 
      </header>
      <div class="table-responsive">
        <table id="data-users" class="table table-striped m-b-none" data-ride="datatables">
          <thead>
            <tr>
              <th>No</th>
              <th>Name</th>
              <th>Email</th>
              <th>Roles</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            @foreach($data as $key=> $item)
            <tr>
              <td>{{$item->id}}</td>
              <td>{{$item->name}}</td>
              <td>{{$item->email}}</td>
              <td>@if(!empty($item->roles))
			  	  @foreach($item->roles as $v)
					<label class="label label-success">{{ $v->display_name }}</label>
				    @endforeach
			      @endif</td>
              <td><a class="btn btn-info btn-xs" href="{{ route('users.edit',$item->id) }}">Edit</a>
                  {!! Form::open(['method' => 'DELETE','route' => ['users.destroy', $item  ->id],'style'=>'display:inline']) !!}
                  {!! Form::submit('Delete', ['class' => 'btn btn-danger btn-xs']) !!}
                  {!! Form::close() !!}</td>
            </tr>
            @endforeach
          </tbody>
        </table>
      </div>
    </section>
  </section>
@endsection