routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
Auth::routes();
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::group(['middleware' => 'auth'], function () {
Route::get('/', 'DashboardController@index');
Route::get('/home', 'HomeController@index');
Route::resource('categories','ProductCategoryController');
Route::resource('types','ProductTypeController');
Route::resource('products','ProductController',['only'=>['index', 'show', 'edit', 'create', 'store', 'update', 'destroy']]);
Route::get('/import_product','ProductController@indexImport');
Route::post('/proses_import','ProductController@prosesImport');
Route::get('product-number','ProductController@sizeNumber');
Route::get('product-size','ProductController@size');
Route::get('product-types','ProductController@type');
Route::get('payment-types','ProductController@payment');    
Route::get('product-category','ProductController@productCategory');
Route::resource('customers','CustomerController',['only'=>['index', 'show', 'edit', 'create', 'store', 'update', 'destroy']]);
Route::get('customers/edit/{id}', 'CustomerController@edit');
Route::resource('receipts', 'ReceiptController',['only'=>['index', 'show', 'create', 'store']]);
Route::get('/loadProducts','ReceiptController@loadProduct');
Route::get('/addOrder','ReceiptController@addOrder');

Route::resource('sales_orders','SalesOrderController',['only'=>['index', 'show', 'create', 'store']]);
Route::get('/findCustomer', 'SalesOrderController@findCustomer' );
Route::get('/loadProductSales', 'SalesOrderController@loadProductSales');
Route::get('/addSalesOrder', 'SalesOrderController@addOrder');
Route::resource('users','UserController');
Route::resource('roles','RoleController');
Route::resource('report_so','ReportSoController');
Route::get('report_so_daily','ReportSoController@salesOrderDaily');
Route::get('roles/edit/{id}', 'RoleController@edit');
Route::get('/report_by_customer', 'CustomerController@reportCustomer');
Route::get('/report_by_po','ProductController@receiptWeek');
Route::get('/report_by_sell','ProductController@sellWeek');
Route::get('/report_so_by_range', 'ReportSoController@index');
Route::resource('report_stock','StockProductController');
Route::get('/export_product','StockProductController@exportExcelProduct');
Route::get('/report_mounth','ReportSoController@salesOrderMounth');
Route::get('/print_data_report','ReportSoController@printDataSellout');
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    
    protected $fillable = ['product_type_id','product_size_id','product_size_number_id','product_category_id','name','price_list','sale_price','qty','picture','active'];


    public function type(){
    	return $this->belongsTo('App\ProductType','product_type_id');
    }

    public function size(){
    	return $this->belongsTo('App\ProductSize','product_size_id');
    }

    public function category(){
    	return $this->belongsTo('App\ProductCategory','product_category_id');
    }


    public function number(){
        return $this->belongsTo('App\ProductSizeNumber','product_size_number_id');
    }

    public function receipt()
    {
        return $this->belongsToMany('App\Receipt','receipt_items');
    }

    public function receipt_items()
    {
        return $this->hasMany('App\ReceiptItem');
    }

    public function sales_order_items()
    {
        return $this->hasMany('App\SalesOrderItem');
    }

    public function setProductType($request)
    {
    $product_type = ProductType::where('name', $request->input('product_type_id',false))->get()->first();
    if(is_null($product_type)){
      $product_type = ProductType::create(['name'=>$request->input('product_type_id',false)]);
    }
    return $product_type->id;
    }


    public function setProductSize($request)
    {
    $product_size = ProductSize::where('name', $request->input('product_size_id',false))->get()->first();
    if(is_null($product_size)){
      $product_size = ProductSize::create(['name'=>$request->input('product_size_id',false)]);
    }
    return $product_size->id;
    }

    public function setProductNumber($request)
    {
    $product_number = ProductSizeNumber::where('name', $request->input('product_size_number_id',false))->get()->first();
    if(is_null($product_number)){
      $product_number = ProductSizeNumber::create(['name'=>$request->input('product_size_number_id',false)]);
    }
    return $product_number->id;
    }

    public function setImportCategory($value)
    {
        $categories = ProductCategory::where('name', $value->category)->get()->first();
        if(is_null($categories)){
            $categories = ProductCategory::create(['name'=> $value->category]);
        }
        return $categories->id;
    }

    public function setImportType($value)
    {
        $type = ProductType::where('name', $value->type)->get()->first();
        if(is_null($type)){
            $type = ProductType::create(['name'=>$value->type]);
        }
        return $type->id;
    }

    public function setImportSize($value)
    {
        $sizes = ProductSize::where('name', $value->size)->get()->first();
        if(is_null($sizes)){
            $sizes = ProductSize::create(['name'=>$value->size]);
        }
        return $sizes->id;
    }

    public function setImportSizeNumber($value)
    {
        $size_numbers = ProductSizeNumber::where('name', $value->size_number)->get()->first();
        if(is_null($size_numbers)){
            $size_numbers = ProductSizeNumber::create(['name'=>$value->size_number]);
        }
        return $size_numbers->id;
    }

    public function historyReceipt($start_date = null, $end_date = null)
    {
        return $this->receipt_items->where('receipt_order.receipt_date', ">=", $start_date)->where('receipt_order.receipt_date', "<=", $end_date);
    }

    public function historySo($start_date = null, $end_date = null)
    {
     return $this->sales_order_items->where('sales_order.sales_date', ">=", $start_date)->where('sales_order.sales_date', "<=", $end_date);
    }


}

app/ProductType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ProductType extends Model
{
    protected $fillable = ['name'];
    public function product(){
    	return $this->hasMany('App\Product');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Product;
use App\ProductCategory;
use App\ProductSizeNumber;
use App\ProductType;
use App\ProductSize;
use App\EdcPayment;
use Input;
use Flash;
use Excel;
class ProductController extends Controller
{

  public function __construct()
  {
    $this->middleware('auth');
  }

   public function index(Request $request){
  
      $products = Product::with('type','category','size','number')->where('active','=',true)->get();
    if($request->ajax()) {
      return response()->json(['aaData' => $products]);
    }
   return view('products.index')->with('products', $products);
      
   }

   public function create(){
    $category = ProductCategory::pluck('name','id');
    return view('products.create',compact('category'));
   }

   public function show($id){
    $product = Product::find($id);
    return view('products.show',compact('product'));
   }

   public function store(Request $request){
      if(Input::hasFile('picture')){
      $extension = Input::file('picture')->getClientOriginalExtension(); // getting image extension
      $fileName = rand(11111,99999).'.'.$extension;
      $destinationPath = "uploads/products";
      $picture = Input::file('picture')->move($destinationPath, $fileName);
    }else{
      $picture = "uploads/products/default.jpg";
    }

    $product = new Product;
    $save_product = Product::create([
      'product_category_id' => $request->input('product_category_id'),
      'name' => $request->input('name'),
      'product_type_id' => is_null($request->input('product_type_id')) ? 1 : $product->setProductType($request),
      'product_size_id' => is_null($request->input('product_size_id')) ? 1 : $product->setProductSize($request),
      'product_size_number_id' => is_null($request->input('product_size_number_id')) ? 1 : $product->setProductNumber($request),
      'sale_price' => $request->input('sale_price',false),
      'picture' => $picture,
      'active' => true
      ]
    );
    flash('Product was successfully created', 'success');
    return redirect('products');
   }

   public function edit($id){
      $category = ProductCategory::pluck('name','id');
      $product = Product::findOrFail($id);
      return view('products.edit',compact('product', 'category'));
   }

   public function update($id, Request $request){
      $product = Product::findOrFail($id);

    if(Input::hasFile('picture')){
      $extension = Input::file('picture')->getClientOriginalExtension(); // getting image extension
      $fileName = rand(11111,99999).'.'.$extension;
      $destinationPath = "uploads/products";
      $picture = Input::file('picture')->move($destinationPath, $fileName);
    }else{
      $picture = $product->picture;
    }

    $product->update([
      'product_category_id' => $request->input('product_category_id'),
      'name' => $request->input('name'),
      'product_type_id' => is_null($request->input('product_type_id')) ? 1 : $product->setProductType($request),
      'product_size_id' => is_null($request->input('product_size_id')) ? 1 : $product->setProductSize($request),
      'product_size_number_id' => is_null($request->input('product_size_number_id')) ? 1 : $product->setProductNumber($request),
      'sale_price' => $request->input('sale_price',false),
      'picture' => $picture,
      'active'  => true,
      ]
    );
    flash('Product was successfully updated', 'success');
    return redirect('products');
   }


   public function destroy(Request $request)
   {
      $product = Product::find($request->id);
         if($request->ajax())
            {
               $product->update(['active'=>false]);
               return response()->json(['status' => true]);
            }
         return redirect('products');
   }
     

  public function productCategory(Request $request)
  {
    $category = ProductCategory::find($request->cat);
    if($request->ajax()){
      $html = view("products.include.".strtolower($category->name))->renderSections();
      return response()->json(['html' => $html]);
    }
  }


   public function sizeNumber(Request $request)
   {
    if($request->ajax())
    {
      $numbers = ProductSizeNumber::where('name', 'LIKE', '%'.$request->input('term').'%')->get();
      $value = array();
      foreach($numbers as $number){
        array_push($value, $number->name);
      }
      return response()->json($value);
    }else{
      $number = ProductSizeNumber::find($request->id);
      return view('products.number')->with('number', $number);
    }
  }

  public function type(Request $request)
   {
    if($request->ajax())
    {
      $types = ProductType::where('name', 'LIKE', '%'.$request->input('term').'%')->get();
      $value = array();
      foreach($types as $type){
        array_push($value, $type->name);
      }
      return response()->json($value);
    }else{
      $type = ProductType::find($request->id);
      return view('products.type')->with('type', $type);
    }
  }

    public function payment(Request $request)
   {
    if($request->ajax())
    {
      $payment = EdcPayment::where('name', 'LIKE', '%'.$request->input('term').'%')->get();
      $value = array();
      foreach($payment as $payments){
        array_push($value, $payments->name);
      }
      return response()->json($value);
    }else{
      $payment = EdcPayment::find($request->id);
      return view('products.type')->with('payment', $payments);
    }
  }

  public function size(Request $request)
   {
    if($request->ajax())
    {
      $sizes = ProductSize::where('name', 'LIKE', '%'.$request->input('term').'%')->get();
      $value = array();
      foreach($sizes as $size){
        array_push($value, $size->name);
      }
      return response()->json($value);
    }else{
      $size = ProductSize::find($request->id);
      return view('products.size')->with('size', $size);
    }
  }

  public function receiptWeek(Request $request)
  {
    if($request->ajax())
      $start_date = $request->from_date;
      $end_date   = $request->to_date;
      $product  = Product::find($request->id);
      $trans  = $product->historyReceipt($start_date,$end_date);
      $html = view("products.report.report_receipt", compact('trans'))->renderSections();
        return response()->json(['html' => $html]);
    return view("products.report.report_receipt")->with('transcation',$transcation);
  }

  public function sellWeek(Request $request)
  {
    if($request->ajax())
      $start_date = $request->from_date;
      $end_date   = $request->to_date;
      $product  = Product::find($request->id);
      $trans  = $product->historySo($start_date,$end_date);
      $html = view("products.report.report_sellout", compact('trans'))->renderSections();
        return response()->json(['html' => $html]);
    return view("products.report.report_sellout")->with('transcation',$transcation);
  }

  public function indexImport(){
    return view('products.import');
  }


  public function prosesImport(Request $request){
      if(Input::hasFile('picture')){
      $extension = Input::file('picture')->getClientOriginalExtension(); // getting image extension
      $fileName = rand(11111,99999).'.'.$extension;
      $destinationPath = "uploads/products";
      $picture = Input::file('picture')->move($destinationPath, $fileName);
    }else{
      $picture = "uploads/products/default.jpg";
    }

     if(Input::hasFile('excel')){
            $path = Input::file('excel')->getRealPath();
            $data = Excel::load($path, function($reader) {
            })->get();


        if(!empty($data) && $data->count()){
            foreach ($data as $key => $rows) {
                        $product = new Product;
                            Product::create([
                                'product_category_id' => $product->setImportCategory($rows),
                                'product_type_id' => $product->setImportType($rows),
                                'product_size_id' => $product->setImportSize($rows),
                                'product_size_number_id' => $product->setImportSizeNumber($rows),
                                'name' => $rows->artikel,
                                'price_list' => $rows->price_list,
                                'sale_price' => $rows->sale_price,
                                'qty' => 0,
                                'picture' => $picture,
                                'active' => 1 
                            ]);
                    }
                    return redirect('products');
                }
            }
            return back();
    }


}

resources/views/products/create.blade.php
@extends('layouts.default')
@section('content')
<section class="panel panel-default">
  <header class="panel-heading font-bold">Insert Product Master</header>
  <div class="panel-body">
    {!! Form::open(['url' => 'products', 'class' => 'form-horizontal','files' => true]) !!}
      <div class="form-group">
        <label class="col-sm-2 control-label">Category</label>
        <div class="col-sm-4">
          {{Form::select('product_category_id',$category,null,['id'=>'category_product','class' => 'form-control chosen-select','placeholder'=>'Select Category','required'=>true])}}
        </div>
      </div>
      <div id='category-spec'>
        <!-- render data -->
      </div>
      
      <div class="line line-dashed b-b line-lg pull-in"></div>

      <div class="form-group">
        <label class="col-sm-2 control-label" for="input-id-1">Product Name</label>
        <div class="col-sm-6">
          {{Form::text('name',null,['class' => 'form-control','id'=>'name','required'=>true,'onkeydown'=>'getNameProduct()','placeholrder'=>'Tab for get name product'])}}
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-2 control-label" for="input-id-1">Sale Price</label>
        <div class="col-sm-2">
          {{Form::text('sale_price',null,['class' => 'form-control','id'=>'sale_price','required'=>true,'onkeypress'=>'return isNumber(event)'])}}
        </div>
      </div>

      <div class="form-group">
          <label class="col-sm-2 control-label" for="input-id-1">Minimun Qty</label>
          <div class="col-sm-2">
              {{Form::number('minimum_qty',null,['class' => 'form-control','id'=>'minimum_qty','required'=>true])}}
          </div>
      </div>

      <div class="form-group">
        <img src="" style="display:none;" alt="product-image" class="image-products img-responsive"/>
      </div>
      <div class="form-group">
        <label class="col-sm-2 control-label">Get Picture</label>
        <div class="col-sm-6">
        <!-- image-preview-filename input [CUT FROM HERE]-->
            <div class="input-group image-preview">
                <input type="text" name="picture" onchange="readURL(this)" class="form-control image-preview-filename" disabled="disabled"> <!-- don't give a name === doesn't send on POST/GET -->
                <span class="input-group-btn">
                    <!-- image-preview-clear button -->
                    <button type="button" class="btn btn-default image-preview-clear" style="display:none;">
                        <span class="glyphicon glyphicon-remove"></span> Clear
                    </button>
                    <!-- image-preview-input -->
                    <div class="btn btn-default image-preview-input">
                        <span class="glyphicon glyphicon-folder-open"></span>
                        <span class="image-preview-input-title">Browse</span>
                        <input type="file" name="picture" accept="image/png, image/jpeg, image/gif" name="input-file-preview"/> <!-- rename it -->
                    </div>
                </span>
            </div><!-- /input-group image-preview [TO HERE]--> 
          {{-- {{Form::file('picture',['class' => 'filestyle','data-icon' => 'false','data-classButton' => 'btn btn-default' ,'data-classInput' => 'form-control inline v-middle input-s','onchange'=>"readURL(this)", 'data-image'=>".image-products"])}} --}}
        </div>
      </div>      
      <div class="line line-dashed b-b line-lg pull-in"></div>
      
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-4">
          {!! Form::submit('Create', ['class' => 'btn btn-primary form-control','id' => 'submit']) !!}
        </div>
      </div>
    {{Form::close()}}
  </div>
</section>	
@endsection

resources/views/products/edit.blade.php
@extends('layouts.default')
@section('content')
<section class="panel panel-default">
  <header class="panel-heading font-bold">Edit Product Master</header>
  <div class="panel-body">
    {!! Form::open(['url' => route('products.update', $product->id), 'method' => 'put', 'class' => 'form-horizontal','files' => true]) !!}
      <div class="form-group">
        <label class="col-sm-2 control-label">Category</label>
        <div class="col-sm-4">
          {{Form::select('product_category_id',$category,$product->product_category_id,['id'=>'category_product','class' => 'form-control chosen-select','placeholder'=>'Select Category','required'=>true])}}
        </div>
      </div>
      <div id='category-spec'>
      @include('products.edit.'.strtolower($product->category->name));
      </div>
      
      <div class="line line-dashed b-b line-lg pull-in"></div>

      <div class="form-group">
        <label class="col-sm-2 control-label" for="input-id-1">Product Name</label>
        <div class="col-sm-6">
          {{Form::text('name',$product->name,['class' => 'form-control','id'=>'name','required'=>true,'onkeydown'=>'getNameProduct()','placeholrder'=>'Tab for get name product'])}}
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-2 control-label" for="input-id-1">Sale Price</label>
        <div class="col-sm-2">
          {{Form::text('sale_price',$product->sale_price,['class' => 'form-control','id'=>'sale_price','required'=>true,'onkeypress'=>'return isNumber(event)'])}}
        </div>
      </div>

      <div class="form-group">
          <label class="col-sm-2 control-label" for="input-id-1">Minimun Qty</label>
          <div class="col-sm-2">
              {{Form::number('minimum_qty',$product->minimum_qty,['class' => 'form-control','id'=>'minimum_qty','required'=>true])}}
          </div>
      </div>

      <div class="form-group">
        <img src="" style="display:none;" alt="product-image" class="image-products img-responsive"/>
      </div>
      <div class="form-group">
        <label class="col-sm-2 control-label">Get Picture</label>
        <div class="col-sm-6">
        <div class="input-group image-preview">
                <input type="text" name="picture" onchange="readURL(this)" class="form-control image-preview-filename" disabled="disabled"> <!-- don't give a name === doesn't send on POST/GET -->
                <span class="input-group-btn">
                    <!-- image-preview-clear button -->
                    <button type="button" class="btn btn-default image-preview-clear" style="display:none;">
                    
                        <span class="glyphicon glyphicon-remove"></span> Clear
                    </button>
                    <!-- image-preview-input -->
                    <div class="btn btn-default image-preview-input">
                        <span class="glyphicon glyphicon-folder-open"></span>
                        <span class="image-preview-input-title">Browse</span>
                        <input type="file" name="picture" accept="image/png, image/jpeg, image/gif" name="input-file-preview"/> <!-- rename it -->
                    </div>
                </span>
            </div>
          {{-- {{Form::file('picture',['class' => 'filestyle','data-icon' => 'false','data-classButton' => 'btn btn-default' ,'data-classInput' => 'form-control inline v-middle input-s','onchange'=>"readURL(this)", 'data-image'=>".image-products"])}} --}}
        </div>
      </div>     
      <div class="line line-dashed b-b line-lg pull-in"></div>
      
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-4">
          {!! Form::submit('Update', ['class' => 'btn btn-primary form-control','id' => 'submit']) !!}
        </div>
      </div>
    {{Form::close()}}
  </div>
</section>  
@endsection

resources/views/products/import.blade.php
@extends('layouts.default')
@section('content')
<section class="panel panel-default">
    <header class="panel-heading font-bold">
	Import Product
    </header>
    <div class="panel-body">
    {!! Form::open(['url' => '/proses_import', 'class' => 'form-horizontal','files' => true]) !!}
        <div class="form-group">
          <label class="col-sm-2 control-label" for="input-id-1">Files</label>
        	<div class="col-sm-4">
              <input type="file" id="excel" name="excel" calss="form-control" accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" required>
        </div>
        </div>
    <div class="line line-dashed b-b line-lg pull-in"></div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-4">
            {!! Form::submit('Import', ['class' => 'btn btn-sm btn-info pull-right','id' => 'submit']) !!}
        </div>
    </div>
    </div>
    {{Form::close()}}
    </div>
</section>	
@endsection

resources/views/products/index.blade.php
@extends('layouts.default')
@section('content')
<section class="scrollable padder">
  <section class="panel panel-default">
<header class="panel-heading">
  Data Products 
  <a href="{{ URL('products/create') }}" class="btn btn-primary pull-right btn-sm">Add Product</a> <a href="{{URL('import_product')}}" class="btn btn-info pull-right btn-sm">Import Product</a><br>
  <i class="fa fa-info-sign text-muted" data-toggle="tooltip" data-placement="bottom" data-title="ajax to load the data."></i> 
</header>
<div class="table-responsive" style="
    overflow-y: auto;">
  <table id="data-products"  class="table table-striped m-b-none" data-ride="datatables">
    <thead>
      <tr>
        <th>Artikel</th>
        <th>Qty</th>
        <th>Sale</th>
        <th>Category</th>
        <th>Type</th>
        <th>Size</th>
        <th>Size Number</th>
        <th>View</th>
      </tr>
    </thead>
    <tbody>
    </tbody>
  </table>
</div>
</section>
</section>
@endsection

resources/views/products/number.blade.php
@extends('layouts.default')
@section('content')
<section class="vbox">
  <section class="scrollable padder">
    <div class="m-b-md">
      <h3 class="m-b-none">
        <a href="{{ URL('products') }}" class="btn btn-primary"><i class="i i-circleleft text"></i>&nbsp; Back</a>
      </h3>
      <br>
      <header class="panel-heading">
      Data Product by Number <b>{{$number->name}}</b>
    </header>
    <section class="panel panel-default">
      <div class="table-responsive">
        <table class="table table-striped b-t b-light">
          <thead>
            <tr>
              <th>Name</th>
              <th>Category</th>
              <th>qty</th>
            </tr>
          </thead>
          <tbody>
            @foreach($number->product as $product)
              <tr>
                <td><a href="{{route('products.show', $product->id)}}">{{$product->name}}</a></td>
                <td>{{$product->category->name}}</td>
                <td>{{$product->qty}}</td>
              </tr>
            @endforeach
          </tbody>
        </table>
      </div>
    </section>
</section>
</section>
@endsection

resources/views/products/size.blade.php
@extends('layouts.default')
@section('content')
<section class="vbox">
  <section class="scrollable padder">
    <div class="m-b-md">
      <h3 class="m-b-none">
        <a href="{{ URL('products') }}" class="btn btn-primary"><i class="i i-circleleft text"></i>&nbsp; Back</a>
      </h3>
      <br>
      <header class="panel-heading">
      Data Product by Size <b>{{$size->name}}</b>
    </header>
    <section class="panel panel-default">
      <div class="table-responsive">
        <table class="table table-striped b-t b-light">
          <thead>
            <tr>
              <th>Name</th>
              <th>Category</th>
              <th>qty</th>
            </tr>
          </thead>
          <tbody>
            @foreach($size->product as $product)
              <tr>
                <td><a href="{{route('products.show', $product->id)}}">{{$product->name}}</a></td>
                <td>{{$product->category->name}}</td>
                <td>{{$product->qty}}</td>
              </tr>
            @endforeach
          </tbody>
        </table>
      </div>
    </section>
</section>
</section>
@endsection

resources/views/products/type.blade.php
@extends('layouts.default')
@section('content')
<section class="vbox">
  <section class="scrollable padder">
    <div class="m-b-md">
      <h3 class="m-b-none">
        <a href="{{ URL('products') }}" class="btn btn-primary"><i class="i i-circleleft text"></i>&nbsp; Back</a>
      </h3>
      <br>
      <header class="panel-heading">
      Data Product by Type <b>{{$type->name}}</b>
    </header>
    <section class="panel panel-default">
      <div class="table-responsive">
        <table class="table table-striped b-t b-light">
          <thead>
            <tr>
              <th>Name</th>
              <th>Category</th>
              <th>qty</th>
            </tr>
          </thead>
          <tbody>
            @foreach($type->product as $product)
              <tr>
                <td><a href="{{route('products.show', $product->id)}}">{{$product->name}}</a></td>
                <td>{{$product->category->name}}</td>
                <td>{{$product->qty}}</td>
              </tr>
            @endforeach
          </tbody>
        </table>
      </div>
    </section>
</section>
</section>
@endsection